### ISSUE TITLE
Product Addons For Shop Products

### ISSUE THREAD

**Issue by petecharles80** [woocommerce/facebook-for-woocommerce#145]
Hi, Great Plugin!!
I'm using the Woocommerce Product Add-Ons Plugin and noticed that when a customer clicks 'Check Out On Website' on the Facebook Shop product, it directs them to the checkout where there's an error message as they haven't filled in the personalised add-on fields. Are there plans to integrate this add-ons functionality directly within the Facebook Shop Products? I've noticed that Shopify sellers have this functionality already.
Many thanks!

**Comment by tahoff** [comment]
@petecharles80, thanks for raising this issue. We are not currently building a fix for this issue, bu

We have a known issue with certain other plugins or variations cause incorrect add-to-cart behavior with respect to shops, there's a workaround you can do by sending users to the product page instead of the add to cart page. It's described in #4.

**Comment by dmitridr** [comment]
To re-iterate on this old issue : we aren't actively building support for this, and encourage everyone to use the workaround for now, but if anyone wants to jump in and build this, we'll be happy to review your pull request!

**Comment by mengyingdu** [comment]
Upload a screen shot to help you find it.
![screen shot 2018-06-27 at 2 00 56 pm](https://user-images.githubusercontent.com/24535640/41999558-ba1aa5be-7a12-11e8-96a0-edf79e32bca9.png)

**Comment by helgatheviking** [comment]
Bringing this back as I have the same issue with my Name Your Price plugin. @mengyingdu I believe the workaround described in #4 is insufficient. Linking to checkout for products that support it and linking to the product page for products that do not, should be automatic. 

WooCommerce itself handles this in the shop loop by testing the following condition:

```
$product->supports( 'ajax_add_to_cart' ) && $product->is_purchasable() && $product->is_in_stock()
```
So it's possible to do and the benefit of doing so would be dramatically increased compatibility with WooCommerce.com marketplace plugins such as Mix and Match Products, product bundles, composite products, product-addons, name your price, etc.

The purchasable and stock status are already in the WooCommerce Rest API, which I assume it what you are using to fetch/sync products to the Facebook app that controls their display in FB itself. 

**My proposal** 
1. Submit PR to add `supports` to WooCommerce product API response
2. Use the new `supports` in conjunction with existing `stock_status` and `purchasable` to recreate the shop loop logic condition
3. If ajax add to cart is supported and purchasable and in stock, display 'checkout' and link to checkout, automatically adding the product to the cart (maintaining the existing functionality for simple products)
4. If one of the conditions is _not_ met display 'view product | select options' and link to product page
5. even better if the button text can be pulled from the API too. Currently the `button_text` product property in the API response is only for external product types, but either it could be made to do more or you could support a custom property. I'd add support for it in my plugin so that my product type gets the appropriate text.

**Comment by helgatheviking** [comment]
@dmitridr could we add the `supports( 'ajax' )` to the info synced? Or does it need to be explicitly in the WooCommerce API? Where can we see the code that handles the display on the FB side?

**Comment by helgatheviking** [comment]
Actually now the product object has the `has_options()` method correct? If the product has options then it should link to the single product page. This could resolve a lot of compatibility issues.

**Comment by budzanowski** [comment]
With the latest changes announced by Meta we will not be working on this.

**Comment by helgatheviking** [comment]
What changes are those?

**Comment by budzanowski** [comment]
The general changes to FB and Instagram shops where Meta is slowly going away from `Check Out On Website` feature. So far in limited locations but I think that this will be expanded soon. Given the low traction of this issue, this should happen before we will ever get to this. I am happy to re-popen in case you think that this should still be open. 

https://www.facebook.com/business/help/623552069600842
