### ISSUE TITLE
Very high CPU usage

### ISSUE THREAD

**Issue by kfaer** [woocommerce/facebook-for-woocommerce#1704]
When enabled this plugin my sever CPU usage goes extremely high

**Comment by arymaynart** [comment]
Same problem here.
I have a VM with 1 core. 100% of cpu usage.
Updated to 2 cores. 100% of cpu usage.
I have less then 2000 products.
I disable the plugin and every thing is fine.
CPU usage below 20% with 40% peeks max.
I belive is something with the job that runs every 15 minutes.

**Comment by serdarwork** [comment]
CPU usage is really high!

I use a server which is fully optimized for WordPress: (LEMP Stack) Nginx 1.19.5 + MariaDB 10.5 (Table engine: innoDB) + PHP7.4-FPM (With Opcode Cache) + Memcached, It still consumes %80 of 4 CPU cores. Impossible to use Memcached (or Redis) Object Cache with this plugin because it wastes Memcached by pushing a lot of data (1GB of data in one hour). As @arymaynart said, something with the job that runs every 15 minutes.

The website has 3400 products in total.

**Comment by GeoJunkie** [comment]
I believe this may be related to #1708

**Comment by lewebsimple** [comment]
Loading a 18 Mb JSON file (fb_google_category_to_attribute_mapping.json) and decoding to get category attribute mappings in memory seems very wasteful.
A better approach could involve storing these in a custom database table and loading only what is needed (object caching would also kick in).

**Comment by galapogos01** [comment]
Yep I was getting OOM errors on the action scheduler job to create the feed. I deselected the google product category and the job now completes successfully.

**Comment by lewebsimple** [comment]
@galapogos01 how did you delelect the google product category ?!?

**Comment by galapogos01** [comment]
In the Product Sync tab.

**Comment by DaveKun** [comment]
I'm having the same problem. My server has a 16-core processor, 128gb of RAM and the CPU load goes up to 100 during the execution of wp cronjobs because of this plugin, if I disable it, everything goes back to normal.

**Comment by danielbitzer** [comment]
With the "18 Mb JSON file" that has been fixed in 2.4.0!

The generate feed memory usage is also a known issue that we are working on for 2.5.0. See #1904

Closing in favor of #1904
