### ISSUE TITLE
Plugin causing site to crash

### ISSUE THREAD

**Issue by SNCasey1988** [woocommerce/facebook-for-woocommerce#1717]
Hi, we use Facebook for WooCommerce however were unable to add or edit any products.

After investigating this we have established that the cause of the problem was the plugin Facebook for WooCommerce.

With the plugin disabled we are now able to view and edit products again; could this be due to a clash following the most recent WooCommerce update?

This is the 2nd time the plugin has caused errors on our site.  The last time was on 27 October.  Our site went down, and an update to the plugin was released the same day which fixed the error.

Here is the error message:

Error Details
=============
An error of type E_ERROR was caused in line 47 of the file /home/XXXXX/public_html/wp-content/plugins/facebook-for-woocommerce/includes/Products/FBCategories.php. Error message: Allowed memory size of 268435456 bytes exhausted (tried to allocate 4096 bytes)

WordPress version 5.5.3
Current theme: Konte Child Theme (version 1.0.0)
Current plugin: Facebook for WooCommerce (version 2.2.0)
PHP version 7.4.12

Thanks,
Sophie

**Comment by gilvandev** [comment]
Same problem on WordPress 5.6

**Comment by zdenys** [comment]
We have various reports of WooCommerce.com users experiencing the same error using Facebook for WooCommerce version 2.2.

**Comment by olsonrebecca** [comment]
We are also experiencing this issue, and have reported it to Automattic. I am not positive, but believe it is related to the Elementor page builder (when disabling Elementor, I can make adjustments to products with Facebook for Woocommerce enabled.) Unfortunately, since my site is built with Elementor I can't disable Elementor without the site looking terrible - so my only option is to disable the Facebook plugin. I don't know if it's Elementor specific, or "page builder" specific, etc. -  Just wanted to put that information out there in case it helps.

**Comment by danielbitzer** [comment]
This was fixed by #1853 and possibly other memory fixes we shipped in version 2.4.0.
