### ISSUE TITLE
Products sync twice (with different Content-ID) 

### ISSUE THREAD

**Issue by muhackl** [woocommerce/facebook-for-woocommerce#1723]
## 🔎 Isolate the bug

- [X] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [X] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.
- Woocommerce 4.7.1, Facebook for Woocommerce 2.2.0, Wordpress 5.5.3

## ✍️ Describe the bug
When I create a new product in Woocommerce, it syncs to my Facebook Business Suite. 
Unfortunately, a doublicate is created or it syncs twice - I don't know.
There is one thing you can tell both apart. If the SKU is e.g. 9876, the "Content ID" of one of the doublettes is 9876_9876 and the one of the other is wc_post_id_9876.
How can I avoid this doublette?

##🚶‍♀️ Steps to reproduce

1. Generate new product in Woocommerce.
2. Save it.
3. Wait for the facebook for woocommerce plugin to sync it.
4. Look at facebook business suit.
5. Find the product twice with two different content ids

## ✔️ Expected behavior

I would like to have the sync to generate just one product in Facebook Business Suite. I almost don't care, what content id it has.

## 🗃 Logs

-

**Comment by haszari** [comment]
Hi @muhackl  - thanks for reporting. This can happen if the SKU or ID of your products is changed, because the Content ID is based on the SKU and Product ID from WooCommerce.

<img width="795" alt="111920909-8e5d5000-8af6-11eb-9a60-2f40cd68ebe8" src="https://user-images.githubusercontent.com/4167300/112085483-7b7a7680-8bef-11eb-8498-97f7c175315b.png">

If you get duplicate products after changing ID or SKU, you can manually delete the older copy of the product in `Facebook Business > Commerce > Catalogue`.

Are you still experiencing this problem? If so could you provide more details about how to reproduce this bug? Thank you :)

**Comment by budzanowski** [comment]
No answer provided from the reporter, closing as stale.
