### ISSUE TITLE
Duplicated products in FB Shop

### ISSUE THREAD

**Issue by HugoGit39** [woocommerce/facebook-for-woocommerce#1737]
We’re happy to help with this question! Our support team works in our help desk rather than GitHub, though, so please use one of the following tools instead:

## 📖 Read documentation

The [Facebook for WooCommerce documentation](https://docs.woocommerce.com/document/facebook-for-woocommerce/) will help you set up the extension, use its features, and answer frequently asked questions. 

## 👩‍💻 Check forums

The [Facebook for WooCommerce forums](https://wordpress.org/support/plugin/facebook-for-woocommerce/) let you review other user questions and issues and learn what worked for them. 

## 🗣 Contact support

Our support team would be happy to help answer your questions! [Click here to get in touch with support.](https://woocommerce.com/my-account/create-a-ticket/)

**Comment by HugoGit39** [comment]
Hi

So I have my products setup correctly in Woocommerce and are synced with the FB Shop. However last weekend I changed some product pics and now certain products are duplicated in the FB SHop. Why? See the screenshot. https://ibb.co/vxzhL3V

**Comment by haszari** [comment]
Thanks for reporting this @HugoGit39. 

I've seen duplicate products in my testing too. For me this happens when I change the SKU of a product; there are products in Facebook shop with the old and new SKU. The Facebook `Content ID` field uses a combination of SKU and Woo product ID. For example:

<img width="795" alt="111920909-8e5d5000-8af6-11eb-9a60-2f40cd68ebe8" src="https://user-images.githubusercontent.com/4167300/112083312-aa8ee900-8beb-11eb-89c2-296ad697dbb9.png">


If this issue is still affecting your store, can you give us more details so we can track down the problem?

**Comment by budzanowski** [comment]
> If this issue is still affecting your store, can you give us more details so we can track down the problem?
No answer provided, closing as stale.
