### ISSUE TITLE
Create product sync validator 

### ISSUE THREAD

**Issue by danielbitzer** [woocommerce/facebook-for-woocommerce#1929]
A class or similar that validates whether a product should be synced to Facebook.

This should support both the batch API update and the feed.

Part of #1904 epic.

**Comment by danielbitzer** [comment]
@woocommerce/tetris does anyone know why we should be doing this:

> allow simple or variable products (and their variations) with zero or empty price - exclude other product types with zero or empty price

https://github.com/woocommerce/facebook-for-woocommerce/blob/9b1a1dcb696fe4e1926b9f196b0375705fad4c41/includes/Products.php#L233-L236

**Comment by danielbitzer** [comment]
Also I though all variable products were not synced to Facebook but rather only the `variations` get synced. Is that correct?

**Comment by haszari** [comment]
> allow simple or variable products (and their variations) with zero or empty price - exclude other product types with zero or empty price

@danielbitzer I suspect that's because the parent variations need to be synched, and legitimately have no price - they are a "container" for the child variations. (guessing)

<img width="924" alt="Screen Shot 2021-05-07 at 3 34 48 PM" src="https://user-images.githubusercontent.com/4167300/117394172-c3f4b600-af49-11eb-8e4e-4564b65d603a.png">

**Comment by budzanowski** [comment]
More info https://github.com/woocommerce/facebook-for-woocommerce/pull/1468

**Comment by danielbitzer** [comment]
@budzanowski are aware of any bugs with the existing code that validates whether a product should sync to Facebook?
