### ISSUE TITLE
Disabling product sync globally

### ISSUE THREAD

**Issue by aidvu** [woocommerce/facebook-for-woocommerce#2022]
## 🔎 Isolate the bug

- [X] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [X] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## ✍️ Describe the bug

While trying to disable the product sync entirely, was told by @haszari to use `wc_facebook_legacy_feed_file_generation_enabled`. This doesn't disable explicitly running the sync via the `wp-admin` interface and clicking `Sync products`.

In the end explicitly disabled the action in `includes/AJAX.php` by returning early in `sync_products`.

Maybe I misunderstood the flag, but I think there should be an easy way to either disable this, or a filter to prevent sync from happening. For sites with a lot of products the sync writes hundreds of GBs to the binary logs, and it's fairly hard to disable.

## 🚶‍♀️ Steps to reproduce

1. Run `wp option set wc_facebook_legacy_feed_file_generation_enabled no` in `wp-cli`
2. Go the the Products tab in the UI and click `Sync products`

## ✔️ Expected behavior
Message is shown that the syncing is disabled.

## 🗃 Logs

<details>
	
</details>

**Comment by haszari** [comment]
There are two mechanisms for product sync in Facebook:

1. Batch API – Woo site pushes changes to Facebook. This is used incrementally – e.g. when products are edited – and also for bulk update – e.g. when clicking `Sync products` in admin
2. Feed – Facebook pulls a feed file, containing all products.

I was mistaken – `wc_facebook_legacy_feed_file_generation_enabled` disables generating the feed file, which has performance issues on larger stores. The reported performance issue appears to be due to the [background sync](https://github.com/woocommerce/facebook-for-woocommerce/blob/master/includes/Products/Sync.php#L76) which uses the Batch API. Gathering the list of product IDs for the full background sync likely has similar scaling issue to the feed.

However, there is a UI option for disabling product sync – so maybe this is useful for the affected site:

<img width="884" alt="Screen Shot 2021-06-16 at 8 36 02 AM" src="https://user-images.githubusercontent.com/4167300/122119947-ee595d80-ce7d-11eb-9823-d54ad51da155.png">

**Comment by aidvu** [comment]
Thanks @haszari. Need a way to disable it so basic users can't re-enable w/o code (options) tinkering. 

When this is something that can break the whole platform, don't want users to be able to run it after simple UI interactions. I guess when the underlying problem gets fixed, a global disable switch won't be needed.

**Comment by haszari** [comment]
Fixed by #2033 (not sure why this didn't close automatically). Closing :)
