### ISSUE TITLE
Retailer ID in product sets instead of Group ID

### ISSUE THREAD

**Issue by rashedripon** [woocommerce/facebook-for-woocommerce#2174]
## 🔎 Isolate the bug

- [x] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [x] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## ✍️ Describe the bug

Facebook plugin is mapping FB product sets to the Retailer_ID instead of the correct, Product Group ID

![image](https://user-images.githubusercontent.com/417342/159728334-f2477f20-f225-4416-a642-5959adce3e40.png)

![image](https://user-images.githubusercontent.com/417342/159728054-c1dc0dc3-20be-43e8-aee8-2593728e6cd0.png)

## 🚶‍♀️ Steps to reproduce

- Create a Product set in **Marketing > Facebook > Product Sets**
- Assing a product category that has variable products in it
- Sync the products
- Check the Sets in the catalog. Use the "View Filter" button.
- There you will see "Retailer ID"

## ✔️ Expected behavior

Not sure if Retailer ID is expected in the product sets. This was first asked in internal support and discussed with dev to report here for clarification: p1647971126835919-slack-C7U3Y3VMY

**Comment by rawdreeg** [comment]
Hi @rashedripon,

Thanks for creating the issue.

> Not sure if Retailer ID is expected in the product sets.

Yes, this is expected behavior. A product set is simply a group of products matching a filter. For example, in the screenshot below, we're matching the products in the set by their Retailer ID:

![Screenshot 2022-07-12 at 17 54 44](https://user-images.githubusercontent.com/4209011/178536546-e7adf405-1d9e-4e3b-9be4-93070111d617.jpg)

This same set could be represented as:

![Screenshot 2022-07-12 at 17 56 01](https://user-images.githubusercontent.com/4209011/178537120-c030a78d-e3bf-447d-b8d5-46e689e735a3.jpg)

The end result is the same. Unless there's a strong argument against how we're bundling the product set (first example), I don't really see why this needs to change.
