### ISSUE TITLE
External/affiliate products are syncing to Facebook but don't have the Facebook product data tab in WC

### ISSUE THREAD

**Issue by sukafia** [woocommerce/facebook-for-woocommerce#2352]
## 🔎 Isolate the bug

External/Affiliate products are syncing to Facebook. However, the Facebook product data tab isn't available on this product type, making it confusing if external/affiliate products are supported. 

- If this product type isn't supported, why are they syncing to Facebook? 
- If they are, why is the Facebook product tab missing for these products? 

## 🚶‍♀️ Steps to reproduce

1. Create an External/Affiliate product
2. Noticed it's synced to Facebook like other products
3. Check product tabs and you'll find no "Facebook" tab exists for controlling Facebook data.

## ✔️ Expected behavior

- Shouldn't sync if it's not a supported product type or the "Facebook" tab should show if it's a supported product type.

**Comment by lynnjat7** [comment]
6020701-zen

**Comment by sukafia** [comment]
6020701-zen

**Comment by nima-karimi** [comment]
@MatthiasReinholz, Could you please weigh in on this issue? We need to figure out if there is any specific business logic behind hiding the Facebook tab for External / Affiliate products even though they are synced with Facebook. If the business requirement is to continue syncing these products, we must display the tab so merchants can manage these products' settings. Otherwise, we should disable the sync for external / affiliate products.

**Comment by nima-karimi** [comment]
Thanks for your input, @sukafia. I agree. It makes sense to enable the tab instead of disabling a long-standing feature. @MatthiasReinholz also believes the same approach should be taken (pb0Spc-3XJ-p2#comment-7565).

I've removed the discussion tag from this issue since this is a confirmed bug we should fix.
