### ISSUE TITLE
Facebook product link not working on Posts

### ISSUE THREAD

**Issue by KMH2017** [woocommerce/facebook-for-woocommerce#2515]
Hi there,
I connected my Woocommerce site to my Facebook shop and have encountered the following problem:
If I post a product with a link to it in the Facebook store (which is synched to my woocommerce), the link does not redirect people to the product in the store. It shows an error screen that states: "this listing no longer exists".
But if I click on the same product in the shop link it comes up fine?

**Comment by KMH2017** [comment]
https://www.facebook.com/kissmyhide is my facebook page showing the posts of products and the failing links.

**Comment by KMH2017** [comment]
https://kissmyhide.com.au/ is my website

**Comment by ecgan** [comment]
Hi @KMH2017 , as noted in our [README.md file](https://github.com/woocommerce/facebook-for-woocommerce/blob/3a98de783439e24e1a43b0d7b667d471ca2e0a99/README.md), the best place to get support is the [WordPress.org Facebook for WooCommerce forum](https://wordpress.org/support/plugin/facebook-for-woocommerce/).

If you have a WooCommerce.com account, you can [start a chat or open a ticket on WooCommerce.com](https://woocommerce.com/my-account/create-a-ticket/).

Closing this issue here.
