### ISSUE TITLE
Some products shown with taxes and others not

### ISSUE THREAD

**Issue by napser1** [woocommerce/facebook-for-woocommerce#2543]
Hi
I have detected that the price of most prodcts extracted from WooCommers is shown with taxes, but there are some products showing the price without tax, which leads to confusion. Is this a bug in the plugin or maybe I am missing something.
Thank you.

**Comment by rawdreeg** [comment]
Hi @napser1,

When a user browses the Facebook page, it doesn't know the shipping address of the viewer. So we can only sync one price (which by default would be the shop address because wc_get_price_to_display is used).

> There are some products showing the price without tax, which leads to confusion. Is this a bug in the plugin or maybe I am missing something?

I'd say this is expected. I suspect that the price display config was changed at some point, which could explain why some products have the price with vs without taxes. We use wc_get_price_to_display to set the price value to match the site. If you need to change the price value, we provide the `wc_facebook_product_price` filter for that purpose.

**Comment by rawdreeg** [comment]
closing as responded with https://github.com/woocommerce/facebook-for-woocommerce/issues/2543#issuecomment-1542046603
