### ISSUE TITLE
Prioritise plugin feed over automatically gathered info from website

### ISSUE THREAD

**Issue by rossodigital** [woocommerce/facebook-for-woocommerce#2784]
It would make sense for the Commerce Manager to prioritize the product title data received via the plugin feed, instead of the SEO title from the website, when the "Automatically update shop with content from your website" option is enabled.

This feature request originated from your Wordpress support forum > https://wordpress.org/support/topic/incorrect-title-in-commerce-manager-feeds/#post-17946613

**Comment by ecgan** [comment]
> It would make sense for the **Commerce Manager** to prioritize the product title data received via the plugin feed, instead of the SEO title from the website, when the **"Automatically update shop with content from your website" option** is enabled.

Hi @rossodigital , it seems to me that this is a feature on the Facebook platform, and it is not something that we control in our plugin. I believe you would need to reach out to Facebook about this feature request.

Related link on Facebook about the feature: [Manage automatic product updates from your website
](https://www.facebook.com/business/help/456992089774836)

Also, in case you are not aware, whenever a product is updated in WooCommerce admin, the changes will be synced automatically to Facebook (see https://woocommerce.com/document/facebook-for-woocommerce/#catalog-syncing for more info). This means that you probably don't need the "Automatically update shop with content from your website" option enabled in Facebook Commerce Manager. 

Since this is not related to our plugin code base here, I'll proceed to close this issue. If you have more questions, feel free to reach out again in the [WordPress.org Facebook for WooCommerce forum](https://wordpress.org/support/plugin/facebook-for-woocommerce/). If you have a WooCommerce.com account, you can [search for help or submit a help request on WooCommerce.com](https://woocommerce.com/my-account/contact-support/).

**Comment by rossodigital** [comment]
Your support team specifically asked me to open this ticket on GitHub for your plugin and not for the Facebook platform... Which I also thought was slightly odd and that's why I even added the Wordpress plugin directory forum link where you can see that your team sent me here.

**Comment by ecgan** [comment]
> that's why I even added the Wordpress plugin directory forum link where you can see that your team sent me here.

Yes, I did read that link. I believe it was a mistake. Our apologies on that. 

> Also, in case you are not aware, whenever a product is updated in WooCommerce admin, the changes will be synced automatically to Facebook (see https://woocommerce.com/document/facebook-for-woocommerce/#catalog-syncing for more info). This means that you probably don't need the "Automatically update shop with content from your website" option enabled in Facebook Commerce Manager.

Just want to be sure and check with you: does the above idea work for you? Are you able to disable the "Automatically update shop with content from your website" option?

**Comment by rossodigital** [comment]
Hi @ecgan - yes we've disabled the option since. It was shown as a recommendation in Commerce Manager so we thought we'd give it a whirl but as in most cases Meta's recommendations actually don't work properly...

**Comment by ecgan** [comment]
> It was shown as a recommendation in Commerce Manager so we thought we'd give it a whirl but as in most cases Meta's recommendations actually don't work properly...

FWIW, my thinking is that it is a general recommendation that applies to most websites in general. For your case here, because you are already using this Facebook extension which automatically sync the changes to Facebook platform for you, and because you have SEO title that differs from the product title, I think it falls outside of the general recommendations.

Anyway, I'm glad that it works out well for you now. If you have any questions, feel free to reach out again.
