### ISSUE TITLE
Auto Create Shop Collections based on Categories

### ISSUE THREAD

**Issue by julienouellette** [woocommerce/facebook-for-woocommerce#34]
Hi,

Is there a way to import categories from my WooCommerce shop into Facebook? Because now all my products are imported in Facebook but i have over a thousand products so it's impossible to navigate through this, and there is no search bar on the mobile version. I saw that we can create a collection but i add products everyday so it would be too complicated. 

Thank you

**Comment by tahoff** [comment]
The categories should be imported to your catalog. If you're referring the Shop Collections, we currently don't auto-create Collections based on the catalog's categories.

**Comment by julienouellette** [comment]
Ok. So there is no other way than to create collections and add product one by one?

**Comment by dmitridr** [comment]
Not as far as I can tell, here's our relevant doc about shop collections: https://www.facebook.com/business/help/1658025111111721

Outside of shops, you can create 'Product Sets' to group items in order to create ads featuring those items. These can be created by using the category field on the product. Here's a link to that doc:

https://www.facebook.com/business/help/620275848114281

**Comment by upravitel** [comment]
I second the feature request stated above by @julienouellette, I have shop with more than 5k products.
And whenever customer wants to access the Facebook shop it takes ages to load, not to mention it does not display all products.

Adding feature where all main product categories get automatically into facebook product collections, will be much more convenient, both for us shop owners and for customers too.

I'm also sure that this is the right direction to reduce slow the slow page loads for Facebook catalogs with thousands of products, like ours...

**Comment by bchevreau** [comment]
I second this feature request! The only thing missing to the amazing addition of WooCommerce integration is the ability for Facebook to retrieve categories, select which categories to sync and create them as collections on the fly. Even for a small shop of about 30-50 products, this is incredibly painful to add. 

To give you a bit of context, here's why it can become a nightmare:

My client currently has a shop selling Gloves for Men and Women with 4 different categories (Female Prestige, Female Standard, Male Prestige, Male Standard). Products have very similar names (as some products exist for both Men and Women, or similar description) and there is little to no indication on the Facebook Shop page as to which is from where. The only thing to do currently is to click each link one by one to verify if the actual product is from a category or another.

Potential fix:

- "easy-dirty fix": Retrieve Woocommerce category as an additional taxonomy in Facebook (so we can see it when displaying the entire list of products while creating collections manually, and add relevant products to collections as it is currently)

- Best fix: On import by Facebook, add a contextual box for adding categories as "Collections", and selecting each category (with the possibility to exclude categories we do not want to display on Facebook) to be treated as collections. 

Note: I believe only first level categories will be taken into account, since I didn't notice any capability for subcategories on Facebook. It should be fine for now, although displaying children categories on import for selection should also be considered.

**Comment by aaroach** [comment]
I would love to see this feature. Any news on whether it will be included in a future release?

**Comment by mengyingdu** [comment]
Given that we're dealing with a high volume of bugs, we unfortunately won't get to this feature request to support automatically creating 'Shop Collections' based on Categories for a long time to come, even though we'd like to. However, we'd be happy to review any pull request to add this functionality, please consider sending us one!

**Comment by Lukacho** [comment]
Any progress regarding collection categories feature?

Even if I create collections manually and move the products there, will they be updated automatically inside that collection when updated in WC?

**Comment by bigrat95** [comment]
Any news on this? it's been months ...

**Comment by chadwickhugh** [comment]
This would be a great addition.  I just installed the extension and Facebook imported my entire shop, with no rhyme or reason to the organization of products.

**Comment by coccoinomane** [comment]
Hello,

Please let me add our use case in order to support the feature request discussed in this issue.

As a web agency we manage a couple of fashion shops which launch a brand new line twice a year (Summer + Winter).

Every time the new season line is out, we have to manually recreate on the FB Shop the same collections that are already present as product categories in the eCommerce.
This process is time consuming and error prone.

It would be ideal if the plugin could (optionally) mirror the eCommerce categories into Facebook Shop Collections. 

Some smart logic would be required to allow the user to select which level of the categories to mirror, or maybe a drag & drop interface to map between eCommerce categories and Facebook Shop Collections; this is not a different implementation from the one discussed in this feature request => https://github.com/facebookincubator/facebook-for-woocommerce/issues/335.

Thank you for your attention,
Guido

**Comment by mrwigster** [comment]
Are there any updates or workarounds for this currently?

**Comment by TrainerMerch** [comment]
We really need some way to generate Facebook Shop Collections based on our Woocommerce categories. Or to even be able to convert Product Sets in the Facebook Catalog Manager into Facebook Shop Collections. I have thousands of products and it is too time consuming to manually create Facebook Shop Collections just based off of the product names. If I was given more of my product data to work with rather than just the product name then that would even help out more.

**Comment by didomenicom** [comment]
I just launched a store on Facebook that is tied to our WooCommerce website with a lot of different products where we really need this functionality as well. 

Admittedly I am not well versed in the social media side of things, but I have done some basic research into the Facebook Graph API for collections and could not figure out what is needed. If I could get a little bit of guidance, I would be more than happy to write a sync script and contribute it back to this plugin.

**Comment by Vikizz** [comment]
We really need this functionality, please find some time for that

**Comment by DanielSalas236** [comment]
I had this issue like 30 min ago. I didn't found any solution on internet.
Solution for me:
- Delete all catalogs of the facebook store (1 catalog in my case). Now when you go to the fan page - > store, it will you a message to create the store.
-Create the store (don't add any product).
-Go to "manage connection" in the plugin settings.
![image](https://user-images.githubusercontent.com/45217116/80239577-19ec0980-8626-11ea-8e24-b7551d0b2094.png)
- Go to advanced settings and delete.
![image](https://user-images.githubusercontent.com/45217116/80239666-4142d680-8626-11ea-867e-95b7f0026927.png)
 - Now cofigure the plugin again.
-Go to "ad settings" -> "Facebook store" -> click in that option (in my case it shows "Show / view" cause i already cofigured this option).

**Comment by DanielSalas236** [comment]
I had this issue like 30 min ago. I didn't found any solution on internet.
Solution for me:
- Delete all catalogs of the facebook store (1 catalog in my case). Now when you go to the fan page - > store, it will you a message to create the store.
- Create the store (don't add any product).
- Go to "manage connection" in the plugin settings.
![image](https://user-images.githubusercontent.com/45217116/80240302-39cffd00-8627-11ea-8e81-af1d2afe05a5.png)
- Go to advanced settings and delete.
![image](https://user-images.githubusercontent.com/45217116/80239666-4142d680-8626-11ea-867e-95b7f0026927.png)
 - Now cofigure the plugin again.
- Go to "ad settings" -> "Facebook store" -> click in that option (in my case it shows "Show / view" cause i already cofigured this option).
![image](https://user-images.githubusercontent.com/45217116/80247995-b0bfc280-8634-11ea-8c76-e49870bba35c.png)

**Comment by lgfogle** [comment]
Hey there,

I wanted to share that we are planning to address category / collection syncing in a future release! While I don't have an exact timeline for when this will be ready, since we have other development work that we've committed to with Facebook and WooCommerce, I'll update this post once we know more.

Thank you!
Lindsey

**Comment by grigorijurasov** [comment]
Requested in 3678290-zen as well.

**Comment by urikanonov** [comment]
Hi, is there any news on this feature request?
I require it as well

Thanks,
Uri

**Comment by rawdreeg** [comment]
Product sets can be created based on Store Categories. I will close this issue.
